# ConfigMap for DB config
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: capstone734834.database.windows.net
  DB_PORT: "1433"
  DB_NAME: weather

---

# Secret for DB credentials
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_USER: c2FuamVlYjE=           # base64 for "sanjeeb1"
  DB_PASS: U2FuamFpZGFkYUAyMDU1   # base64 for "Sanjaidada@2055"

---

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # Keep 1 for easier debugging
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_BACKEND
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
          readinessProbe:
            httpGet:
              path: /api/user
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/user
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---

# Backend NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000